"""baseline schema

Revision ID: 328de383cbc9
Revises: 
Create Date: 2026-07-27 00:26:31.660619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


EXPECTED_TABLES = {
    "ai_cache",
    "background_jobs",
    "daily_expansion_quizzes",
    "daily_mission_tasks",
    "email_action_tokens",
    "grammar_concept_bank",
    "grammar_error_ledger",
    "gsat_reference_papers",
    "mock_exam_attempts",
    "mock_exam_sets",
    "refresh_tokens",
    "review_sync_receipts",
    "users",
    "user_vocab_progress",
    "vocabulary",
    "writing_evaluations",
}


# revision identifiers, used by Alembic.
revision: str = '328de383cbc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    inspector = sa.inspect(op.get_bind())
    existing_tables = set(inspector.get_table_names()) - {"alembic_version"}
    if existing_tables:
        missing_tables = EXPECTED_TABLES - existing_tables
        if missing_tables:
            missing = ", ".join(sorted(missing_tables))
            raise RuntimeError(
                "Refusing to adopt a partial GSAT_Max schema. "
                f"Missing tables: {missing}"
            )
        return

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_hash', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=120), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_cache_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_cache_endpoint'), ['endpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_cache_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_cache_prompt_hash'), ['prompt_hash'], unique=False)

    op.create_table('grammar_concept_bank',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('example_sentence', sa.Text(), nullable=True),
    sa.Column('gsat_level', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grammar_concept_bank', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammar_concept_bank_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_concept_bank_gsat_level'), ['gsat_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_concept_bank_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_concept_bank_name'), ['name'], unique=True)

    op.create_table('gsat_reference_papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('exam_type', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('json_structure', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gsat_reference_papers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gsat_reference_papers_exam_type'), ['exam_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_gsat_reference_papers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_gsat_reference_papers_year'), ['year'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('essays_written', sa.Integer(), nullable=False),
    sa.Column('grammar_score_total', sa.Float(), nullable=False),
    sa.Column('grammar_score_count', sa.Integer(), nullable=False),
    sa.Column('last_login_date', sa.DateTime(), nullable=True),
    sa.Column('current_streak', sa.Integer(), nullable=False),
    sa.Column('daily_ai_quota', sa.Integer(), nullable=False),
    sa.Column('quota_reset_date', sa.DateTime(), nullable=False),
    sa.Column('is_pro', sa.Boolean(), nullable=False),
    sa.Column('has_completed_onboarding', sa.Boolean(), nullable=False),
    sa.Column('skill_vocabulary', sa.Float(), nullable=False),
    sa.Column('skill_grammar', sa.Float(), nullable=False),
    sa.Column('skill_reading', sa.Float(), nullable=False),
    sa.Column('skill_writing', sa.Float(), nullable=False),
    sa.Column('target_exam_date', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('vocabulary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=120), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('part_of_speech', sa.String(length=40), nullable=True),
    sa.Column('gsat_level', sa.Integer(), nullable=True),
    sa.Column('gsat_frequency', sa.Integer(), nullable=True),
    sa.Column('source_context', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vocabulary_gsat_frequency'), ['gsat_frequency'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_gsat_level'), ['gsat_level'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vocabulary_word'), ['word'], unique=True)

    op.create_table('background_jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_background_jobs_idempotency_key'), ['idempotency_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_background_jobs_job_type'), ['job_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_background_jobs_user_id'), ['user_id'], unique=False)

    op.create_table('daily_mission_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('mission_date', sa.Date(), nullable=False),
    sa.Column('task_key', sa.String(length=120), nullable=False),
    sa.Column('task_type', sa.String(length=80), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'mission_date', 'task_key', name='uq_daily_mission_task')
    )
    with op.batch_alter_table('daily_mission_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_mission_tasks_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_mission_tasks_mission_date'), ['mission_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_mission_tasks_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_mission_tasks_task_type'), ['task_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_mission_tasks_user_id'), ['user_id'], unique=False)

    op.create_table('email_action_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_action_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_action_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_action_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_action_tokens_purpose'), ['purpose'], unique=False)
        batch_op.create_index(batch_op.f('ix_email_action_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_email_action_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('grammar_error_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=120), nullable=False),
    sa.Column('original_sentence', sa.Text(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('corrected_sentence', sa.Text(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('is_mastered', sa.Boolean(), nullable=False),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grammar_error_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_grammar_error_ledger_error_type'), ['error_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_error_ledger_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_error_ledger_is_mastered'), ['is_mastered'], unique=False)
        batch_op.create_index(batch_op.f('ix_grammar_error_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('mock_exam_sets',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=120), nullable=False),
    sa.Column('difficulty', sa.String(length=80), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('rubric_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_exam_sets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_exam_sets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_exam_sets_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_exam_sets_version'), ['version'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('replaced_by_jti', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_revoked_at'), ['revoked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('review_sync_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_sync_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_sync_receipts_action_id'), ['action_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_review_sync_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sync_receipts_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_sync_receipts_vocab_id'), ['vocab_id'], unique=False)

    op.create_table('user_vocab_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vocab_id', sa.Integer(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('ease_factor', sa.Float(), nullable=False),
    sa.Column('next_review_date', sa.DateTime(), nullable=False),
    sa.Column('last_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vocab_id'], ['vocabulary.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vocab_id', name='uq_user_vocab_progress')
    )
    with op.batch_alter_table('user_vocab_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_next_review_date'), ['next_review_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_vocab_progress_vocab_id'), ['vocab_id'], unique=False)

    op.create_table('writing_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('essay_type', sa.String(length=80), nullable=False),
    sa.Column('original_essay', sa.Text(), nullable=False),
    sa.Column('prompt_image_present', sa.Boolean(), nullable=False),
    sa.Column('evaluation_json', sa.Text(), nullable=False),
    sa.Column('rubric_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('writing_evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_writing_evaluations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_evaluations_essay_type'), ['essay_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_evaluations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_writing_evaluations_user_id'), ['user_id'], unique=False)

    op.create_table('daily_expansion_quizzes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('grammar_error_id', sa.Integer(), nullable=True),
    sa.Column('concept', sa.String(length=120), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('options_json', sa.Text(), nullable=False),
    sa.Column('correct_option_index', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('source_job_id', sa.String(length=64), nullable=True),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['grammar_error_id'], ['grammar_error_ledger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('daily_expansion_quizzes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_daily_expansion_quizzes_concept'), ['concept'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_expansion_quizzes_due_date'), ['due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_expansion_quizzes_grammar_error_id'), ['grammar_error_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_expansion_quizzes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_expansion_quizzes_source_job_id'), ['source_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_expansion_quizzes_user_id'), ['user_id'], unique=False)

    op.create_table('mock_exam_attempts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('exam_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('answers_json', sa.Text(), nullable=False),
    sa.Column('original_translation', sa.Text(), nullable=True),
    sa.Column('original_essay', sa.Text(), nullable=True),
    sa.Column('evaluation_json', sa.Text(), nullable=False),
    sa.Column('rubric_version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['mock_exam_sets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mock_exam_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mock_exam_attempts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_exam_attempts_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mock_exam_attempts_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mock_exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_exam_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_mock_exam_attempts_exam_id'))
        batch_op.drop_index(batch_op.f('ix_mock_exam_attempts_created_at'))

    op.drop_table('mock_exam_attempts')
    with op.batch_alter_table('daily_expansion_quizzes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_expansion_quizzes_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_expansion_quizzes_source_job_id'))
        batch_op.drop_index(batch_op.f('ix_daily_expansion_quizzes_id'))
        batch_op.drop_index(batch_op.f('ix_daily_expansion_quizzes_grammar_error_id'))
        batch_op.drop_index(batch_op.f('ix_daily_expansion_quizzes_due_date'))
        batch_op.drop_index(batch_op.f('ix_daily_expansion_quizzes_concept'))

    op.drop_table('daily_expansion_quizzes')
    with op.batch_alter_table('writing_evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_writing_evaluations_user_id'))
        batch_op.drop_index(batch_op.f('ix_writing_evaluations_id'))
        batch_op.drop_index(batch_op.f('ix_writing_evaluations_essay_type'))
        batch_op.drop_index(batch_op.f('ix_writing_evaluations_created_at'))

    op.drop_table('writing_evaluations')
    with op.batch_alter_table('user_vocab_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_vocab_id'))
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_next_review_date'))
        batch_op.drop_index(batch_op.f('ix_user_vocab_progress_id'))

    op.drop_table('user_vocab_progress')
    with op.batch_alter_table('review_sync_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_sync_receipts_vocab_id'))
        batch_op.drop_index(batch_op.f('ix_review_sync_receipts_user_id'))
        batch_op.drop_index(batch_op.f('ix_review_sync_receipts_id'))
        batch_op.drop_index(batch_op.f('ix_review_sync_receipts_action_id'))

    op.drop_table('review_sync_receipts')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_revoked_at'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_expires_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('mock_exam_sets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mock_exam_sets_version'))
        batch_op.drop_index(batch_op.f('ix_mock_exam_sets_user_id'))
        batch_op.drop_index(batch_op.f('ix_mock_exam_sets_created_at'))

    op.drop_table('mock_exam_sets')
    with op.batch_alter_table('grammar_error_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_error_ledger_user_id'))
        batch_op.drop_index(batch_op.f('ix_grammar_error_ledger_is_mastered'))
        batch_op.drop_index(batch_op.f('ix_grammar_error_ledger_id'))
        batch_op.drop_index(batch_op.f('ix_grammar_error_ledger_error_type'))

    op.drop_table('grammar_error_ledger')
    with op.batch_alter_table('email_action_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_action_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_email_action_tokens_token_hash'))
        batch_op.drop_index(batch_op.f('ix_email_action_tokens_purpose'))
        batch_op.drop_index(batch_op.f('ix_email_action_tokens_id'))
        batch_op.drop_index(batch_op.f('ix_email_action_tokens_expires_at'))

    op.drop_table('email_action_tokens')
    with op.batch_alter_table('daily_mission_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_daily_mission_tasks_user_id'))
        batch_op.drop_index(batch_op.f('ix_daily_mission_tasks_task_type'))
        batch_op.drop_index(batch_op.f('ix_daily_mission_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_daily_mission_tasks_mission_date'))
        batch_op.drop_index(batch_op.f('ix_daily_mission_tasks_id'))

    op.drop_table('daily_mission_tasks')
    with op.batch_alter_table('background_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_background_jobs_user_id'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_job_type'))
        batch_op.drop_index(batch_op.f('ix_background_jobs_idempotency_key'))

    op.drop_table('background_jobs')
    with op.batch_alter_table('vocabulary', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vocabulary_word'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_id'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_gsat_level'))
        batch_op.drop_index(batch_op.f('ix_vocabulary_gsat_frequency'))

    op.drop_table('vocabulary')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('gsat_reference_papers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gsat_reference_papers_year'))
        batch_op.drop_index(batch_op.f('ix_gsat_reference_papers_id'))
        batch_op.drop_index(batch_op.f('ix_gsat_reference_papers_exam_type'))

    op.drop_table('gsat_reference_papers')
    with op.batch_alter_table('grammar_concept_bank', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_grammar_concept_bank_name'))
        batch_op.drop_index(batch_op.f('ix_grammar_concept_bank_id'))
        batch_op.drop_index(batch_op.f('ix_grammar_concept_bank_gsat_level'))
        batch_op.drop_index(batch_op.f('ix_grammar_concept_bank_category'))

    op.drop_table('grammar_concept_bank')
    with op.batch_alter_table('ai_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_cache_prompt_hash'))
        batch_op.drop_index(batch_op.f('ix_ai_cache_id'))
        batch_op.drop_index(batch_op.f('ix_ai_cache_endpoint'))
        batch_op.drop_index(batch_op.f('ix_ai_cache_created_at'))

    op.drop_table('ai_cache')
    # ### end Alembic commands ###
