"""learning momentum and weekly print packs

Revision ID: 9c52b7f79fd4
Revises: 328de383cbc9
Create Date: 2026-08-01 12:16:56.422248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c52b7f79fd4'
down_revision: Union[str, Sequence[str], None] = '328de383cbc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_progress_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('source_key', sa.String(length=160), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('skill', sa.String(length=40), nullable=True),
    sa.Column('outcome', sa.String(length=40), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_progress_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_progress_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_event_date'), ['event_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_outcome'), ['outcome'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_skill'), ['skill'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_source_key'), ['source_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_learning_progress_events_user_id'), ['user_id'], unique=False)

    op.create_table('learning_reward_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_points', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('comeback_count', sa.Integer(), nullable=False),
    sa.Column('streak_shields', sa.Integer(), nullable=False),
    sa.Column('last_active_date', sa.Date(), nullable=True),
    sa.Column('last_shield_refill_week', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_learning_reward_state')
    )
    with op.batch_alter_table('learning_reward_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_reward_states_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reward_states_last_active_date'), ['last_active_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_learning_reward_states_user_id'), ['user_id'], unique=False)

    op.create_table('user_learning_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weekday_minutes', sa.Integer(), nullable=False),
    sa.Column('weekend_minutes', sa.Integer(), nullable=False),
    sa.Column('preferred_session_minutes', sa.Integer(), nullable=False),
    sa.Column('rescue_session_minutes', sa.Integer(), nullable=False),
    sa.Column('maximum_session_minutes', sa.Integer(), nullable=False),
    sa.Column('weekly_goal_days', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('gentle_streak_enabled', sa.Boolean(), nullable=False),
    sa.Column('paper_pack_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_learning_preference')
    )
    with op.batch_alter_table('user_learning_preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_learning_preferences_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_learning_preferences_user_id'), ['user_id'], unique=False)

    op.create_table('weekly_study_packs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('pack_code', sa.String(length=12), nullable=False),
    sa.Column('daily_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('completed_days_json', sa.Text(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('last_downloaded_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start', name='uq_weekly_study_pack')
    )
    with op.batch_alter_table('weekly_study_packs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weekly_study_packs_pack_code'), ['pack_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_weekly_study_packs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_study_packs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_weekly_study_packs_week_start'), ['week_start'], unique=False)

    with op.batch_alter_table('daily_mission_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.String(length=20), nullable=False, server_default='foundation'))
        batch_op.add_column(sa.Column('success_target', sa.Float(), nullable=False, server_default='0.85'))
        batch_op.add_column(sa.Column('reward_points', sa.Integer(), nullable=False, server_default='10'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_mission_tasks', schema=None) as batch_op:
        batch_op.drop_column('reward_points')
        batch_op.drop_column('success_target')
        batch_op.drop_column('difficulty')

    with op.batch_alter_table('weekly_study_packs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weekly_study_packs_week_start'))
        batch_op.drop_index(batch_op.f('ix_weekly_study_packs_user_id'))
        batch_op.drop_index(batch_op.f('ix_weekly_study_packs_status'))
        batch_op.drop_index(batch_op.f('ix_weekly_study_packs_pack_code'))

    op.drop_table('weekly_study_packs')
    with op.batch_alter_table('user_learning_preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_learning_preferences_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_learning_preferences_id'))

    op.drop_table('user_learning_preferences')
    with op.batch_alter_table('learning_reward_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_reward_states_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_reward_states_last_active_date'))
        batch_op.drop_index(batch_op.f('ix_learning_reward_states_id'))

    op.drop_table('learning_reward_states')
    with op.batch_alter_table('learning_progress_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_user_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_source_key'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_skill'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_outcome'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_id'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_event_date'))
        batch_op.drop_index(batch_op.f('ix_learning_progress_events_created_at'))

    op.drop_table('learning_progress_events')
    # ### end Alembic commands ###
